[project]
name = "artcollab"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/ArtCollab/artcollab/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.contribution-manager]
path = "contracts/contribution-manager.clar"

[contracts.ownership-manager]
path = "contracts/ownership-manager.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
